name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: build
          build-root-directory: app
      - run: make checkstyleMain
      - run: make test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 61b985c380c213a8c5437b2d8356ae9178671e8e636cb061276cb7d5fe60827b
          JACOCO_SOURCE_PATH: /app/src/main/java
        with:
          coverageCommand: app/.gradlew jacocoTestReport
          coverageLocations: /app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
