#name: Java CI
#
#on:
#  - push
#  - pull_request
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#      - uses: gradle/gradle-build-action@v3
#        with:
#          gradle-version: 8.7
#          arguments: build
#          build-root-directory: app
#      - run: make checkstyleMain
#      - run: make test
#      - name: Prepare CC Reporter
#        run: ./cc-reporter before-build
#        env:
#          CC_TEST_REPORTER_ID: 61b985c380c213a8c5437b2d8356ae9178671e8e636cb061276cb7d5fe60827b
#      - name: Publish code coverage
#        uses: paambaati/codeclimate-action@v9.0.0
#        env:
#          CC_TEST_REPORTER_ID: 61b985c380c213a8c5437b2d8356ae9178671e8e636cb061276cb7d5fe60827b
#          JACOCO_SOURCE_PATH: /app/src/main/java
#        with:
#          coverageCommand: app/gradlew
#          coverageLocations: /app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Проверка кода
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Установка Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Установка Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      # 4. Запуск линтера Checkstyle
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
        working-directory: ./app

      # 5. Запуск тестов
      - name: Run Tests
        run: ./gradlew test
        working-directory: ./app

      # 6. Генерация отчета покрытия
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport
        working-directory: ./app

      # 7. Отправка покрытия кода в Code Climate
      - name: Download Code Climate Test Reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-reporter

      - name: Set Execute Permissions
        run: chmod +x ./cc-reporter

      - name: Prepare CC Reporter
        run: ./cc-reporter before-build
        env:
          CC_TEST_REPORTER_ID: 61b985c380c213a8c5437b2d8356ae9178671e8e636cb061276cb7d5fe60827b

      - name: Upload Coverage to Code Climate
        run: |
          ./cc-reporter format-coverage ./app/build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
          ./cc-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: 61b985c380c213a8c5437b2d8356ae9178671e8e636cb061276cb7d5fe60827b